package Views;

import Models.Configuracao;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author Gabriel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static Configuracao model;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
    }

    public FrmPrincipal(Configuracao model) {
        this();
        this.model = model;
        this.iniciaFormulario();
    }

    private void colocarFormularioCentro(JInternalFrame frame) {
        Dimension desktopSize = this.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    public boolean verificaLogin() {
        if (this.model.getFuncionario() == null) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstop = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jmiLivro = new javax.swing.JMenuItem();
        jmEmprestimo = new javax.swing.JMenu();
        jmDevolucao = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout dekstopLayout = new javax.swing.GroupLayout(dekstop);
        dekstop.setLayout(dekstopLayout);
        dekstopLayout.setHorizontalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        dekstopLayout.setVerticalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jmCadastros.setText("Cadastros");
        jmCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrosActionPerformed(evt);
            }
        });

        jmiAluno.setText("Aluno");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiAluno);

        jmiFuncionario.setText("Funcionário");
        jmCadastros.add(jmiFuncionario);

        jmiLivro.setText("Livro");
        jmCadastros.add(jmiLivro);

        menu.add(jmCadastros);

        jmEmprestimo.setText("Emprestimo");
        menu.add(jmEmprestimo);

        jmDevolucao.setText("Devolução");
        menu.add(jmDevolucao);

        jmSair.setText("Sair");
        jmSair.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jmSairMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        menu.add(jmSair);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setBounds(0, 0, 779, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrosActionPerformed
    }//GEN-LAST:event_jmCadastrosActionPerformed

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        this.dekstop.removeAll();
        if (this.verificaLogin()) {
            FrmCadastrarAluno frmCadastrarAluno = new FrmCadastrarAluno(this.model);
            this.dekstop.add(frmCadastrarAluno);
            this.colocarFormularioCentro(frmCadastrarAluno);
            frmCadastrarAluno.setVisible(true);
        } else {
            FrmLogin frmLogin = new FrmLogin(this.model);
            this.dekstop.add(frmLogin);
            this.colocarFormularioCentro(frmLogin);
            frmLogin.setVisible(true);
        }
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (this.model.getFuncionario() == null) {
            FrmLogin frmLogin = new FrmLogin(this.model);
            this.dekstop.add(frmLogin);
            this.colocarFormularioCentro(frmLogin);
            frmLogin.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed

    }//GEN-LAST:event_jmSairActionPerformed

    private void jmSairMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jmSairMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmSairMenuKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstop;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmDevolucao;
    private javax.swing.JMenu jmEmprestimo;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiLivro;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables

    public void iniciaFormulario() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

}
