package Views;

import Models.Configuracao;

/**
 *
 * @author Gabriel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static Configuracao model;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    public FrmPrincipal(Configuracao model) {
        this();
        this.model = model;
        this.iniciaFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dekstop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jmiFuncionario = new javax.swing.JMenuItem();
        jmiLivro = new javax.swing.JMenuItem();
        jmEmprestimo = new javax.swing.JMenu();
        jmDevolucao = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");

        javax.swing.GroupLayout dekstopLayout = new javax.swing.GroupLayout(dekstop);
        dekstop.setLayout(dekstopLayout);
        dekstopLayout.setHorizontalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        dekstopLayout.setVerticalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jmCadastros.setText("Cadastros");
        jmCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastrosActionPerformed(evt);
            }
        });

        jmiAluno.setText("Aluno");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiAluno);

        jmiFuncionario.setText("Funcionário");
        jmCadastros.add(jmiFuncionario);

        jmiLivro.setText("Livro");
        jmCadastros.add(jmiLivro);

        jMenuBar1.add(jmCadastros);

        jmEmprestimo.setText("Emprestimo");
        jMenuBar1.add(jmEmprestimo);

        jmDevolucao.setText("Devolução");
        jMenuBar1.add(jmDevolucao);

        jmSair.setText("Sair");
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );

        setBounds(0, 0, 779, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastrosActionPerformed

    }//GEN-LAST:event_jmCadastrosActionPerformed

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        FrmCadastrarAluno frmCadastrarAluno = new FrmCadastrarAluno(this.model);
        this.dekstop.add(frmCadastrarAluno);
        frmCadastrarAluno.setVisible(true);
    }//GEN-LAST:event_jmiAlunoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmDevolucao;
    private javax.swing.JMenu jmEmprestimo;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiFuncionario;
    private javax.swing.JMenuItem jmiLivro;
    // End of variables declaration//GEN-END:variables

    public void iniciaFormulario() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

}
